[project]
name = "swe-for-ds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "isort>=6.0.0",
    "numpy>=2.2.3",
    "scipy>=1.15.1",
]
